### PR TITLE
10817-Not-So-Smart-Change => main

### PR DESCRIPTION
**Pull request by dustinmoorenet**
### Switch SmartPost to FedEx Ground Economy

ordoro/ordoro#10817

ordoro/shipper-options@71ba4b8e07cacd0b4288dadf67b499929143b3ed

___

### 1.19.1

ordoro/shipper-options@af304da6dd78826e0e6ea838d6e1b534b43d00b3

### CODE REVIEW

**Review by sophieher — APPROVED** [review]

**Comment by sophieher** [comment]
i had one to add if you wanted to add it here
```diff --git ShipperOptions.json ShipperOptions.json
index 5ca858d..6f87d3a 100644
--- ShipperOptions.json
+++ ShipperOptions.json
@@ -1139,7 +1139,7 @@
         "value": "FEDEX_INTERNATIONAL_PRIORITY"
       },
       {
-        "display": "FedEx International Express",
+        "display": "FedEx International Priority Express",
         "value": "FEDEX_INTERNATIONAL_PRIORITY_EXPRESS"
```

**Comment by dustinmoorenet** [comment]
I can do that

**Comment by dustinmoorenet** [comment]
does it have a related issue number?

**Comment by sophieher** [comment]
> does it have a related issue number?

no, i just said i'd change it and then i left it in a changed state locally while you were ooo

**Pull request merged**
